# Default values for my-rails-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
appname: app
sidekiq:
  replicaCount: 1
  name: sidekiq-worker
image:
  repository: fake
  tag: latest
  pullPolicy: Always
service:
  name: app-web-service
  type: LoadBalancer
  targetPort: 3000
  port: 3000
  nodePort: 30001
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  secret:
    RAILS_MASTER_KEY: 'fake'
    SECRET_KEY_BASE: 'fake'
    SMTP_PASSWORD: 'fake'
    BUCKET_NAME: 'fake'
    ACCESS_KEY: 'fake'
    SECRET_KEY: 'fake'
    DEVISE_SECRET: 'fake'
    DB_NAME: 'fake'
    DB_HOST: 'fake'
    DB_PASSWORD: 'fake'
    DB_USERNAME: 'fake'
    REDIS_URL: 'fake'
  normal:
    RAILS_ENV: production
    STORAGE: 'fog'
    SMTP_ADDRESS: ''
    SMTP_PORT: ''
    SMTP_DOMAIN: ''
    SMTP_USERNAME: ''
    MAILER_SENDER: ''
    MAILER_HOST: ''
    RAILS_SERVE_STATIC_FILES: 1
    FOG_PROVIDER: ''
    PROVIDER: ''
    UPLOADER_STORAGE_PATH: ''
db:
  instance: fake
ingress:
  enabled: true
  ipname: app-exchange-ip
  ipAddress: ''
  name: app-ingress

secret:
  env: app-env-secret
  dbInstance: cloudsql-instance-credentials
  dbCreds: cloudsql-db-credentialss